### ISSUE TITLE
Run multiple Deis clusters inside of one Kubernetes cluster

### ISSUE THREAD

**Issue by technosophos** [deis/charts#18] opened 2015-12-04 18:29 UTC
We need to make sure that we can run multiple Deis clusters inside of the same Kubernetes cluster. In fact, it's highly likely that some of our early testers will be using this feature.

This means:
- We should not assume the namespace is "deis"
- We should make sure that the "child" namespaces we create for apps do not collide. We could probably accomplish this by prepending the "parent" namespace to the child (e.g. "wild-socks" becomes "deis1-wild-socks"
- We need to think long and hard about how we handle Ingress

What other things (label queries? service acounts?) are impacted?

**Comment by gabrtv** [comment] 2015-12-04 20:20
+1

**Comment by arschles** [comment] 2015-12-04 20:22
https://github.com/deis/router/pull/18 would be affected because it assumes the "deis" namespace

**Comment by krancour** [comment] 2015-12-04 20:24
@arschles I have a PR to fix that already, but I haven't submitted because I need to rebase to master after deis/router#18 is merged.

**Comment by arschles** [comment] 2015-12-04 20:24
also, deis/builder would be affected because it launches pods to run builds. we'd have to templatize the manifests to set the right namespace. not a big deal, bit worth mentioning

**Comment by bacongobbler** [comment] 2015-12-04 20:28
I'm concerned here about running two workloads on the same cluster. For instance, given this circumstance:
- two "separate" deis clusters on the same kuebernetes cluster
- both create a "staging" user
- both create an application called "mytestapp"
- first cluster pushes the app (fine, creates RC/service)
- second cluster pushes the app <-- ALL HELL BREAKS LOOSE, 500 errors everywhere since service/RC exist
- second cluster scales app to 5 <-- scales rc to 5, whereas first cluster expected only 1 instance

What I'm trying to allude to is that there are going to be more conflicts than just the control plane itself. Were going to have to maintain an entire suite of logic for application deployments just to support this use case, and I don't imagine many users would be doing this in prod anyways.

**Comment by krancour** [comment] 2015-12-04 20:30
@bacongobbler I think this was the reasoning behind:

> We should make sure that the "child" namespaces we create for apps do not collide. We could probably accomplish this by prepending the "parent" namespace to the child (e.g. "wild-socks" becomes "deis1-wild-socks"

**Comment by krancour** [comment] 2015-12-04 20:37
But I do agree there are lots of other considerations.  @technosophos already mentioned it, but ingress is foremost on my mind.

Currently, I'm doing port mappings of host:80/443/2222 to router pod(s):80/443/2222.  This was intended to enable the load balancing strategy used in v1.x.  i.e. Put an ELB in front of the _whole_ cluster and whichever ones happen to be hosting routers will pass the health check.  This has been a deliberate choice _instead_ of using k8s a k8s service for the router with `type: LoadBalancer` because that won't work on infrastructure where the corresponding cloud provider implements that as a no op-- e.g. Vagrant and bare metal.

Obviously, that breaks down if you want to run _two_ Deis clusters (each with their own router mesh) in one k8s cluster.

One option _might_ be to allow _one_ router to manage ingress to multiple Deis control planes (i.e. workflow and builder).  That actually sounds relatively easy.

**Comment by jchauncey** [comment] 2016-07-08 19:23
Can we close this issue for now? I'm guessing we will solve this another way.

**Comment by blurrcat** [comment] 2016-07-09 13:40
Hi guys, what's the status of this?
I'm new to Deis. I assumed I could deploy workflow to another namespace simply by supplying the namespace parameter to helmc install: `helmc install --namespace=staging workflow-v2.1.0`. Apparently it doesn't work that way. I guess I could change all `namespace: deis` lines in manifest files but I doubt if the code assumes the deis namespace too. That also leads to some maintenance headache too. 
We would really love it if both staging and production workflow can be run in a single cluster. Without this, we simply can't use Workflow. Do we have a workaround right now? Is there any suggestion about managing staging/production environments with Workflow? Thanks in advance.

**Comment by jchauncey** [comment] 2016-07-09 15:28
Right now certain components look for other components within the `deis` namespace. So this isnt completely feasible right now.

**Closed as completed** 2017-02-15 23:33 UTC
Labels: question
