### ISSUE TITLE
builder and workflow pods fail to start

### ISSUE THREAD

**Issue by mboersma** [deis/charts#68] opened 2016-01-13 17:07 UTC
With the current deis-dev chart, builder and workflow pods consistently fail to start for me on a new k8s cluster:

``` console
$ kubectl --namespace=deis get po
NAME                        READY     STATUS          RESTARTS   AGE
deis-builder-d6wok          0/1       ImageNotReady   0          5m
deis-database-s8z9l         1/1       Running         0          5m
deis-etcd-1-2p99n           1/1       Running         0          5m
deis-etcd-1-yn4i5           1/1       Running         1          5m
deis-etcd-1-zcubc           1/1       Running         0          5m
deis-etcd-discovery-zi268   1/1       Running         0          5m
deis-minio-qayzv            1/1       Running         0          5m
deis-registry-f7xad         1/1       Running         0          5m
deis-router-o4tmi           1/1       Running         0          5m
deis-workflow-ro7sc         0/1       ImageNotReady   0          5m
```

I can `docker pull` the images in question locally and on the minion node.

**Comment by arschles** [comment] 2016-01-13 17:26
The builder issue is that the `builder-key-auth` secret is missing, and for workflow the issue is the `django-secret-key` secret is missing.

Applicable output from `kd describe pod deis-builder-rkmao`:

``` console
  2m        7s      16  {kubelet gke-aaron-e39d4573-node-7vz4}          FailedSync  Error syncing pod, skipping: secrets "builder-key-auth" not found
```

Applicable output from `kd describe pod deis-workflow-de9ud`:

``` console
  2m        8s      18  {kubelet gke-aaron-e39d4573-node-hecx}          FailedSync  Error syncing pod, skipping: secrets "django-secret-key" not found
```

**To fix this**: run `helm generate deis-dev` before running `helm install deis-dev`

Note that as of now, the `generate` command only works in the `deis-dev` chart (the change was made in #67). The `deis` chart doesn't yet have the necessary templates.

cc/ @helgi since he made the changes in #67

**Comment by arschles** [comment] 2016-01-13 17:27
@mboersma can you confirm that the `helm generate` command fixes and, if it does, close this issue?

**Comment by mboersma** [comment] 2016-01-13 17:30
@arschles yes, today I am playing the role of naive user. Everything is great after `helm generate deis-dev && helm install deis-dev`.

I'll add that to the deis/charts documentation and then consider this issue closed.

**Comment by arschles** [comment] 2016-01-13 17:31
@mboersma :100: thanks

**Comment by helgi** [comment] 2016-01-13 17:38
I hadn't updated the docs yet - just threw it into the channels and most of the PRs. My bad

**Closed as completed** 2016-01-13 18:09 UTC
Labels: bug, showstopper
